Numpy

Numpy is a fundamental library for scientific computer in python. its provide support for array and matrrics, along with acollection of mathmatical function to operate on these data structure in this lesson ,we will cover the basic of Numpy. focusing on array and vectorized operation

pip install numpy

In [2]:
import numpy as np

In [3]:
#  Create the 1 D array:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
print(arr.shape)
print(arr.ndim)


(5,)
1


In [5]:
#  2D array
arr2=np.array([1,2,3,4,5])
arr2.reshape([1,5])
arr2.shape

(5,)

In [6]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.shape)
arr2

(2, 5)


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
#  Create the matrix of 1 
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
#  Create the identity matrix:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#  Numpy vectorized Operation:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element Wise Addition:
print("Addition operation",arr1+arr2)

# Ele,emt wise Subtraction:
print("Subtraction Operation",arr1-arr2)

# Element Wise Multiplication:

print("Multiplication Operation",arr1*arr2)

# Element Wise Division:

print("Division Operation",arr1/arr2)
# 

Addition operation [11 22 33 44 55]
Subtraction Operation [ -9 -18 -27 -36 -45]
Multiplication Operation [ 10  40  90 160 250]
Division Operation [0.1 0.1 0.1 0.1 0.1]


In [11]:
#  Iniversal Function

arr=np.array([1,2,3,4,5,6])

# square root
print(np.sqrt(arr))

# Exponential:
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Log:
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
#  Sclining array and Indexing:
arr=np.array([[1,2,3,4,],[5,6,7,8],[7,8,9,0]])
print("Array:\n",arr)

Array:
 [[1 2 3 4]
 [5 6 7 8]
 [7 8 9 0]]


In [13]:
print(arr[1][2])
#  first show row and secound are show columne
print(arr[0:2 ,2:])

print(arr[1: ,1:3])

7
[[3 4]
 [7 8]]
[[6 7]
 [8 9]]


In [14]:
arr[1: ,2:]

array([[7, 8],
       [9, 0]])

In [15]:
#  Modify the array elements:
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  7   8   9   0]]


In [16]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [17]:
#  Stastical concept: -Normalization

# to have a mean of 0 standard deviation:
data=np.array([1,2,3,4,5])

#  Calcualate the mean and standard deviation
Mean=np.mean(data)
std=np.std(data)

#  Normalization the data:
normalization_data=(data-Mean)/std
print("Normalization data:",normalization_data)

Normalization data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [18]:
#  Clacuate the standard derivation:
arr=np.array([1,2,3,4,5])
# Mean of the array
print("Mean:",np.mean(arr))
# Standard deviation:
std_dev=np.std(arr)
print("Standard Darivation",std_dev)

# Variance:
VAriance=np.var(arr)
print("Variance:",VAriance)

Mean: 3.0
Standard Darivation 1.4142135623730951
Variance: 2.0


In [23]:
# Locial Operation:
data=np.array([1,2,3,4,5,6,7,8,9,10])
#  Retrive the data grater than 5
print(data[(data>5) & (data<8)])

#  Retrive the data small than 8
print(data[data<8])


[6 7]
[1 2 3 4 5 6 7]
