# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

 Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.



In [2]:
import numpy as np
arr=np.random.randint(1,50,size=[5,5])
print(arr)
print("")
arr[2]=1
print(arr)

[[ 4 17 29  4 10]
 [41 20 20 26  5]
 [19  8 36  1 42]
 [26 17  5  2 10]
 [10 20 31  8 22]]

[[ 4 17 29  4 10]
 [41 20 20 26  5]
 [ 1  1  1  1  1]
 [26 17  5  2 10]
 [10 20 31  8 22]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print("")

np.fill_diagonal(arr,0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [4]:
arr=np.arange(1,37).reshape(6,6)
print(arr)
print("")
print(arr[2:5,3:])
print("")

arr_random=np.random.randint(100,size=[5,5])
print(arr_random)

print("")

Border_elements=np.concatenate([
arr_random[0,:],
arr_random[-1,:],
arr_random[1:-1,0],
arr_random[1:-1,-1]]

)
print(Border_elements)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

[[16 17 18]
 [22 23 24]
 [28 29 30]]

[[54 58 10 51 97]
 [51 61 55  7  5]
 [89  4 14 85 60]
 [14 30 32 27  0]
 [70 23 10  3 83]]

[54 58 10 51 97 70 23 10  3 83 51 89 14  5 60  0]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [5]:
arr=np.random.randint(100,size=(3,4))
arr1=np.random.randint(100,size=(3,4))
print(arr,"\n",arr1)

print("")
print(arr+arr1)

print("")
print(arr-arr1)
print("")
print(arr*arr1)
print("")
print(arr/arr1)

[[77 46 93 66]
 [49 41 18 93]
 [17 45 98  3]] 
 [[11 58 11 55]
 [77 35 83 15]
 [35  7 61 21]]

[[ 88 104 104 121]
 [126  76 101 108]
 [ 52  52 159  24]]

[[ 66 -12  82  11]
 [-28   6 -65  78]
 [-18  38  37 -18]]

[[ 847 2668 1023 3630]
 [3773 1435 1494 1395]
 [ 595  315 5978   63]]

[[7.         0.79310345 8.45454545 1.2       ]
 [0.63636364 1.17142857 0.21686747 6.2       ]
 [0.48571429 6.42857143 1.60655738 0.14285714]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [6]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print("")
print("Coloumns -wise sum:",np.sum(arr, axis=0))
print("Row -wise sum     :",np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Coloumns -wise sum: [28 32 36 40]
Row -wise sum     : [10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.



In [7]:
arr=np.random.randint(100,size=(5,5))
print(arr)
print("")
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

[[56 65 90 32  4]
 [30 54 45 45 91]
 [37 22 46  4 45]
 [55 53 81 95 34]
 [18 42 97 62 86]]

51.56
46.0
26.465192234329226
700.4064


. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [8]:
arr=np.arange(1,10).reshape(3,3)
print(arr)
print("Normalization of arr:")
mean=arr.mean()
std=arr.std()

Normalization=(mean-arr)/std
print(Normalization)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalization of arr:
[[ 1.54919334  1.161895    0.77459667]
 [ 0.38729833  0.         -0.38729833]
 [-0.77459667 -1.161895   -1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. 

In [9]:
arr=np.random.randint(100,size=(3,3))
print(arr)

arr1=[1,2,3]

print("")

arr=arr+arr1
print(arr)

[[26 22 51]
 [59 59  3]
 [58 22 44]]

[[27 24 54]
 [60 61  6]
 [59 24 47]]


Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
arr=np.random.randint(100,size=(4,4))
print(arr)

arr1=np.array([1,2,3,4])


print("")

arr=arr-arr1
print(arr)

[[ 0 11  5 88]
 [ 9 51 61 26]
 [94 16 42 77]
 [93 53 31 25]]
(4,)

[[-1  9  2 84]
 [ 8 49 58 22]
 [93 14 39 73]
 [92 51 28 21]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. 

In [45]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[2, 1, 3],
                   [1, 0, 2],
                   [4, 1, 8]])

print("Matrix:")
print(matrix)

# Determinant
det = np.linalg.det(matrix)
print("\nDeterminant:")
print(det)

# Inverse (only if determinant ≠ 0)
if np.isclose(det, 0):
    print("\nInverse:")
    print("Matrix is singular, inverse does not exist.")
else:
    inverse = np.linalg.inv(matrix)
    print("\nInverse:")
    print(inverse)

# Eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("\nEigenvalues:")
print(eigenvalues)


Matrix:
[[2 1 3]
 [1 0 2]
 [4 1 8]]

Determinant:
-1.0

Inverse:
[[ 2.  5. -2.]
 [ 0. -4.  1.]
 [-1. -2.  1.]]

Eigenvalues:
[ 9.88864745  0.37851665 -0.26716411]


Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [54]:
arr=np.array([[1,2,3],[4,5,6]])
arr1=np.array([[5,4],[6,5],[7,5]])
mul=np.dot(arr,arr1)
print(mul)

[[38 29]
 [92 71]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. 


In [60]:
arr=np.arange(1,10).reshape(3,3)
print(arr)
print("reshap the array(1.9)\n",arr.reshape(1,9))
print("REshape the array into (9,1)\n",arr.reshape(9,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
reshap the array(1.9)
 [[1 2 3 4 5 6 7 8 9]]
REshape the array into (9,1)
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [65]:
arr=np.random.randint(100,size=(5,5))
print(arr)
one_d_array=arr.flatten()
print(one_d_array)

one_d_array.reshape(5,5)

[[24 21 49 19  1]
 [90 42 23 83 67]
 [95 96 62 51 96]
 [42 63 78 81 72]
 [39 76 69 23 48]]
[24 21 49 19  1 90 42 23 83 67 95 96 62 51 96 42 63 78 81 72 39 76 69 23
 48]


array([[24, 21, 49, 19,  1],
       [90, 42, 23, 83, 67],
       [95, 96, 62, 51, 96],
       [42, 63, 78, 81, 72],
       [39, 76, 69, 23, 48]], dtype=int32)

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. .


In [83]:
import numpy as np

# Create a 5x5 array with random integers (e.g., from 0 to 99)
arr = np.random.randint(0, 100, size=(5, 5))

print("Original Array:")
print(arr)

# Fancy indexing for corner elements
corner_elements = arr[[0,0,4,4],[0,4,0,4]]

print("\nCorner Elements:")
print(corner_elements)


Original Array:
[[23 67 91 75 66]
 [63 34 35 81  5]
 [77 66 91 60 77]
 [62 75  1 75 59]
 [46 22 51 71 38]]

Corner Elements:
[23 66 46 38]


Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10

In [89]:
arr=np.random.randint(100,size=(4,4))
print(arr)

arr[arr>=10]=10

print("")
print(arr)

[[39 14 80 27]
 [24 72 18 44]
 [ 8  3 97 64]
 [86 49 80 96]]

[[10 10 10 10]
 [10 10 10 10]
 [ 8  3 10 10]
 [10 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2.



In [90]:
import numpy as np
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


 Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [97]:
data_type=[("X","i4"),("Y","i4")]
data=np.array([
    (3,4),(5,6),(7,8),(8,9)
],dtype=data_type)

print(data)
print("")

# Compute Euclidean distance from origin
distances = np.sqrt(data['X']**2 + data['Y']**2)
print(distances)



[(3, 4) (5, 6) (7, 8) (8, 9)]

[ 5.          7.81024968 10.63014581 12.04159458]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. 

In [103]:
masked_array=np.random.randint(100,size=(4,4))
print(masked_array)

mask=masked_array[masked_array>10]
print(mask)

unmask=masked_array[masked_array<=10]
print(unmask)

sum_unmask=unmask.sum()
print(sum_unmask)


[[83 41 60 56]
 [38  2 37 42]
 [91 88  6 36]
 [30 21 49 32]]
[83 41 60 56 38 37 42 91 88 36 30 21 49 32]
[2 6]
8


Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements

In [117]:
import numpy as np

arr = np.random.randint(100, size=(3, 3))
print("Original Array:")
print(arr)

print("\nDiagonal Elements:")
diag = np.diagonal(arr)
print(diag)

# Step 1: Subtract diagonal values properly from each corresponding row/column
# Expand diagonal to a 2D array using reshape or broadcasting
unmask = arr - np.diag(diag)
print("\nArray After Subtracting Diagonal (unmask):")
print(unmask)

# Step 2: Compute mean of the diagonal
mean_diag = np.mean(diag)
print("\nMean of Diagonal:", mean_diag)

# Step 3: Replace diagonal with the mean
np.fill_diagonal(arr, mean_diag)
print("\nFinal Array After Replacing Diagonal with Mean:")
print(arr)


Original Array:
[[68 76 24]
 [30 26 12]
 [83 59 24]]

Diagonal Elements:
[68 26 24]

Array After Subtracting Diagonal (unmask):
[[ 0 76 24]
 [30  0 12]
 [83 59  0]]

Mean of Diagonal: 39.333333333333336

Final Array After Replacing Diagonal with Mean:
[[39 76 24]
 [30 39 12]
 [83 59 39]]
